kind: Deployment
apiVersion: apps/v1
metadata:
  name: smasher-back
  labels:
    app: smasher-back
    app.kubernetes.io/component: smasher-back
    app.kubernetes.io/instance: smasher-back
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: smasher-back
  template:
    metadata:
      labels:
        deployment: smasher-back
    spec:
      volumes:
        - name: sa-volume
          secret:
            secretName: sa-token
            defaultMode: 420
        - name: keys
          configMap:
            name: keys
            defaultMode: 420
      containers:
        - terminationMessagePath: /dev/termination-log
          name: smasher-back
          env:
            - name: KUBERNETES_MASTER
              value: 'https://api.ocp.client.com:6443'
            - name: KUBERNETES_AUTH_SERVICEACCOUNT_TOKEN
              value: /home/jboss/sa/token
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sa-volume
              mountPath: /home/jboss/sa/
            - name: keys
              mounPath: /home/jboss/keys/
          terminationMessagePolicy: File
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
